### ISSUE TITLE
RESEARCH - text field restriction

### ISSUE THREAD

**Issue by Victor-B-dev** [Team-BigBusiness/SayLess#53]
see if a form text field can be restricted based on a string.
see if we can change the restriction (length) depending on different strings.

**Comment by LenaDurant** [comment]
<input class="form-control"
                 id="productNameId"
                 type="text"
                 placeholder="Name (required)"
                 required
                 minlength="3"
                 [(ngModel)]=product.productName
                 name="productName"
                 #productNameVar="ngModel"
                 [ngClass]="{'is-invalid': (productNameVar.touched || 
                                            productNameVar.dirty ||
                                            product.id !== 0) && 
                                            !productNameVar.valid }" />
          <span class="invalid-feedback">
            <span *ngIf="productNameVar.errors?.required">
              Product name is required.
            </span>
            <span *ngIf="productNameVar.errors?.minlength">
              Product name must be at least three characters.
            </span>
          </span>

**Comment by LenaDurant** [comment]
**Approach 1: Using maxLength**
We will use maxLength attribute for our input. It is the same as the maxlength attribute used for HTML. It restricts the user to enter characters till it reaches the maxLength limit that we have set.
Example: This example uses max length attribute to implement the restriction for character input.

**Javascript**

// Filename - App.js

function App() {
	return (
		<div className="App">
			<label>Name:</label>
			<input name="name" type="text" maxLength={10} />
		</div>
	);
}

export default App;


**This would stop an 11th character from populating**

**Comment by LenaDurant** [comment]
<script> 
 function validateLength(mxlength, val, id){ 
 if (val.length > mxlength)  
 document.getElementById(id).value = val.slice(0, mxlength); 
 } 
</script>

**Comment by LenaDurant** [comment]
![Image](https://github.com/user-attachments/assets/45cb80c5-d41f-4e5e-aab1-9dc4b9903de7)
